name: path_drawing
version: 1.0.1
description: >
  A flutter library to help with (Canvas) Path creation and manipulation
homepage: https://github.com/dnfield/flutter_path_drawing

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  meta: ^1.15.0
  path_parsing: ^1.1.0

dev_dependencies:
  path: ^1.8.0
  test: ^1.21.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # There's no need to include these as we don't use them.
  # This fixes an issue when our plugin is imported into a project that also
  # uses no material icons.
  uses-material-design: false

environment:
  sdk: '>=3.0.0 <4.0.0'
